[from-webrtc]
exten => _X.,1,NoOp(Outbound call from ${CALLERID(num)} to ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},45)
 same => n,Hangup()

[from-iagu]
exten => _X.,1,NoOp(Inbound from Iagu: ${EXTEN} caller ${CALLERID(num)})
 same => n,Dial(PJSIP/kartik,45)
 same => n,Hangup()
